import React from "react";

const NavContent = () => {
    return <>
             <div className="nav-content-2 hidden lg:block">
                 <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Omnis harum voluptatum quibusdam cupiditate quam soluta nostrum ea consequuntur velit similique perferendis eligendi aut molestiae, ab voluptas quaerat dolorum, debitis tenetur incidunt numquam placeat magni minima? Vero enim ipsa harum inventore commodi velit eos eaque id fuga, sit magni itaque a incidunt quod veniam ducimus at accusamus repellendus ipsum suscipit? Earum architecto in ut doloremque impedit explicabo. Quae aliquam beatae rem dolorem officia! Voluptates optio laborum quisquam. Reiciendis est explicabo totam. Saepe pariatur, facilis quae vel velit excepturi. Sapiente quam earum numquam nisi obcaecati fugit minima animi deleniti eaque repudiandae alias praesentium nam autem nemo at, beatae assumenda. Harum, facere reprehenderit molestiae expedita veritatis minus? Ducimus dolor possimus, id dolorem nesciunt dolores voluptas, sed voluptatum doloribus quaerat numquam beatae alias harum mollitia tempore totam eius quisquam quos, delectus qui sunt. Magnam fuga quos voluptatum illo repellendus ipsam facere, cupiditate non praesentium inventore veritatis tempore aut deleniti, ab quidem magni error harum incidunt! Sint ipsam officiis ex impedit at sapiente? Porro perspiciatis cupiditate autem hic veritatis qui expedita ex eveniet nemo. Harum dolorem excepturi iste omnis. Voluptas tempora et ab nihil exercitationem at eligendi dolores accusantium vitae. Animi aliquid iusto similique ipsum.</p>
             </div>
             {/* for mobile part */}
             {/* <div className="nav-content-2 block lg:hidden">
                 <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Omnis harum voluptatum quibusdam cupiditate quam soluta nostrum ea consequuntur velit similique perferendis eligendi aut molestiae, ab voluptas quaerat dolorum, debitis tenetur incidunt numquam placeat magni minima? Vero enim ipsa harum inventore commodi velit eos eaque id fuga, sit magni itaque a incidunt quod veniam ducimus at accusamus repellendus ipsum suscipit? Earum architecto in ut doloremque impedit explicabo. Quae aliquam beatae rem dolorem officia! Voluptates optio laborum quisquam. Reiciendis est explicabo totam. Saepe pariatur, facilis quae vel velit excepturi. Sapiente quam earum numquam nisi obcaecati fugit minima animi deleniti eaque repudiandae alias praesentium nam autem nemo at, beatae assumenda. Harum, facere reprehenderit molestiae expedita veritatis minus? Ducimus dolor possimus, id dolorem nesciunt dolores voluptas, sed voluptatum doloribus quaerat numquam beatae alias harum mollitia tempore totam eius quisquam quos, delectus qui sunt. Magnam fuga quos voluptatum illo repellendus ipsam facere, cupiditate non praesentium inventore veritatis tempore aut deleniti, ab quidem magni error harum incidunt! Sint ipsam officiis ex impedit at sapiente? Porro perspiciatis cupiditate autem hic veritatis qui expedita ex eveniet nemo. Harum dolorem excepturi iste omnis. Voluptas tempora et ab nihil exercitationem at eligendi dolores accusantium vitae. Animi aliquid iusto similique ipsum.</p>
             </div> */}
           </>
}

export default NavContent;